export const friendshipQuotes = [
  { quote: "A friend is someone who knows all about you and still loves you.", author: "Elbert Hubbard" },
  { quote: "Friendship is born at that moment when one person says to another, ‘What! You too? I thought I was the only one.’", author: "C.S. Lewis" },
  { quote: "True friendship is when you walk into their house and your WiFi connects automatically.", author: "Unknown" },
  { quote: "A real friend is one who walks in when the rest of the world walks out.", author: "Walter Winchell" },
  { quote: "Friends are the family you choose.", author: "Jess C. Scott" },
  { quote: "Friendship isn’t about who you’ve known the longest, it’s about who walked into your life and said ‘I’m here for you’ and proved it.", author: "Unknown" },
  { quote: "The greatest gift of life is friendship, and I have received it.", author: "Hubert H. Humphrey" },
  { quote: "Friendship doubles your joy and divides your sorrow.", author: "Francis Bacon" },
  { quote: "A true friend accepts who you are, but also helps you become who you should be.", author: "Unknown" },
  { quote: "Friends are like stars. You don’t always see them, but you know they’re always there.", author: "Unknown" },
  { quote: "A single rose can be my garden… a single friend, my world.", author: "Leo Buscaglia" },
  { quote: "Friendship is the only cement that will ever hold the world together.", author: "Woodrow Wilson" },
  { quote: "A true friend is the greatest of all blessings.", author: "Francois de La Rochefoucauld" },
  { quote: "The only way to have a friend is to be one.", author: "Ralph Waldo Emerson" },
  { quote: "True friends are never apart, maybe in distance but never in heart.", author: "Helen Keller" },
  { quote: "A good friend knows all your stories. A best friend helped you write them.", author: "Unknown" },
  { quote: "Friendship is not about who you spend the most time with, it’s about who you have the best time with.", author: "Unknown" },
  { quote: "Friendship is a sheltering tree.", author: "Samuel Taylor Coleridge" },
  { quote: "A friend is one that knows you as you are, understands where you have been, accepts what you have become, and still, gently allows you to grow.", author: "William Shakespeare" },
  { quote: "Friends are those rare people who ask how we are and then wait to hear the answer.", author: "Ed Cunningham" },
  { quote: "It’s not what we have in life, but who we have in our life that matters.", author: "Unknown" },
  { quote: "Friendship is like a rainbow between two hearts.", author: "Unknown" },
  { quote: "A good friend is like a four-leaf clover; hard to find and lucky to have.", author: "Irish Proverb" },
  { quote: "Some people arrive and make such a beautiful impact on your life, you can barely remember what life was like without them.", author: "Anna Taylor" },
  { quote: "Life was meant for good friends and great adventures.", author: "Unknown" },
  { quote: "In the cookie of life, friends are the chocolate chips.", author: "Unknown" },
  { quote: "Best friends make the good times better and the hard times easier.", author: "Unknown" },
  { quote: "Friendship is the golden thread that ties the heart of all the world.", author: "John Evelyn" },
  { quote: "Happiness is having a friend who understands you without saying a word.", author: "Unknown" },
  { quote: "A real friend is like a bright star; they shine even on the darkest days.", author: "Unknown" }
];
